### ISSUE TITLE
A README would be useful

### ISSUE THREAD

**Issue by zpallin** [valarauca/context_bind#1]
Either that or you could run the Rust Doc for this lib.

**Comment by valarauca** [comment]
Both are going to happen 😅. I only got the core stable a few hours ago. This crate needs to have the CPU pool added, as well as affinity settings. You were a bit faster then I was had grocery shopping and work out to do.

**Comment by valarauca** [comment]
I think this should resolve your issue

https://github.com/valarauca/context_bind/blob/master/README.md
